[workspace]
members = ["tools/findbytes"]

[package]
name = "gd_rce_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
