name: build

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools setuptools_rust twine wheel
          python -m pip install --upgrade cibuildwheel

      - name: Build
        run: |
          python setup.py sdist bdist_wheel
          python -m cibuildwheel --output-dir built_wheels

        env:
          # skip 2.7, 3.4, 3.5 and pypy builds
          CIBW_SKIP: "cp27-* cp34-* cp35-* pp*"

      - uses: actions/upload-artifact@v2
        with:
          path: ./built_wheels/*.whl
          path: ./dist/*
